name: Connoisseur
main: cc.isotopestudio.Connoisseur.Connoisseur

author: Mars
description: Connoisseur
website: http://isotopestudio.cc
version: 1.0.0
commands:
  ConnoisseurAdmin:
    description: Connoisseur Admin command
    usage: /<command> - Get Information
    aliases: cadmin